name: React ci pipeline/workflow

on: 
    push:
        branches:
            - main

jobs:
    build-react-ci:
        runs-on: ubuntu-latest

        steps:
            - name: checkout code 
              uses: actions/checkout@v5

            - name: setup node js 
              uses: actions/setup-node@v6
              with:
                node-version: '24'

            - name: install dependencies
              run: npm install

            - name: run the tests
              run: npm test --if-present

            - name: run the bulid
              run: npm run build

            - name: upload the artifact
              uses: actions/upload-artifact@v4
              with:
                name: bulid
                path: dist 